enabled: true

#The mobcoin item type.
#For a head use the format HEAD:(HEAD_URL_HERE), such as HEAD:
#For glass/glass panes, use the format (COLOR)_STAINED_GLASS(_PANE), such as RED_STAINED_GLASS_PANE
item-type: "HEAD:4ad0476e8671696af3a8949afa2a814b9bdde65eccd1a8b593aeeff5a0318d"

pickup-sound: "EXPERIENCE_PICKUP"
pickup-sound-volume: 1
pickup-sound-pitch: 1
send-message-on-pickup: true

disabled-worlds: []

#The height the item should spawn at
y-change-amount: 0.0

#Delay in ticks (20 per second)
pickup-check-delay: 10

#The distance that mobcoins can be picked up from
x-distance: 1.0
y-distance: 1.0
z-distance: 1.0
