# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                         #
#                                   Jak3's jHoppers                                       #
#                                                                                         #
# This plugin is apart of the J-Series for plugins. (jseries.store)                       #
# If you ever need support -                                                              #
# discord.jseries.store                                                                   #
# I hope you all enjoy, I spent a lot of time on the plugin.                              #
# The following plugins have added support:                                               #
# ANY Factions/Skyblock/Claiming plugin, WildStacker, ShopGUIPlus, and SuperBoosters.     #
# Ask me if you would like support for another plugin.                                    #
# Note: guis.yml is for editing the gui designs.                                          #
# Note: messages.yml is for editing the messages.                                         #
#                                                                                         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

#This check will automatically check every x seconds if the hopper blocks are still the correct block.
#If this plugin is lagging you can either turn this value up, or disable it by setting the value 0 or below.
#This value is in seconds.
hopper-block-check: 10
#A notification will be sent if this is true to ops every time the blocks are checked.
send-block-check-notification: true
block-check-notification:
  - "&7*"
  - "&7* CHECKING THE HOPPER BLOCKS"
  - "&7*"

#How often the holograms will update in seconds
hologram-update-time: 5

#SECONDS
#Set to 0 or below to disable
auto-save-time: 300

permissions:
  #The permission to use jhoppers
  use-hopper: "jhoppers.use"
  #The permission to add members to their own jhoppers
  addmembers: "jhoppers.addmembers"
  #The permission to use manage the jhoppers plugin and to give hoppers to players
  admin-permission: "jhoppers.admin"
