main:  store.jseries.pmc.PhysicalMobCoins
name: PhysicalMobCoins
version: ${project.version}
depend:
  - SuperMobCoins
description: ${project.description}
author: Jak3
website: jseries.store
api-version: '1.13'
commands:
  pmc:
    description: Main PMC Command.
    aliases:
      - physicalmobcoins
      - physicalmobcoin
